version: '3.3'
services:
  python-ws:
    image: python-ws:latest
    container_name: python-ws
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - 8080:8080
    expose:
    - 8080

  mysq-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    # Configure mysql service
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - 3306:3306
    expose:
    - 3306
    # Where our data will be persisted
    volumes:
    - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: